version: "3"

services:
  bb_db_server:
    image: postgres
    container_name: bb_db_server
    restart: unless-stopped
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - bb_network
    environment:
      POSTGRES_PASSWORD: 1234554321
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

networks:
  bb_network:
    name: bb_network