# Generated by Django 4.2.11 on 2024-04-22 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bb.rubric', verbose_name='Родительская рубрика')),
            ],
        ),
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(help_text='Текст неограниченной длинны', verbose_name='Описание')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=11)),
                ('curr', models.CharField(max_length=3, verbose_name='Валюта')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bb.rubric', verbose_name='Рубрика')),
            ],
        ),
    ]
