# Generated by Django 4.2.11 on 2024-04-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0002_alter_bulletin_options_alter_rubric_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubric',
            name='name',
            field=models.CharField(default=None, max_length=100, null=True, unique=True, verbose_name='Название'),
        ),
    ]
