# Generated by Django 4.2.11 on 2024-05-29 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0004_alter_rubric_name_alter_rubric_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulletin',
            options={'default_permissions': ('add', 'view', 'change', 'delete', 'alcohol'), 'ordering': ['-rubric', '-cost'], 'permissions': (('alcohol', 'Права на покупку алкоголя'),), 'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterModelOptions(
            name='rubric',
            options={'ordering': ['-name'], 'verbose_name': 'Рубрика', 'verbose_name_plural': 'Рубрики'},
        ),
        migrations.AlterUniqueTogether(
            name='bulletin',
            unique_together={('name', 'description', 'cost')},
        ),
    ]
