# Generated by Django 4.2.11 on 2024-06-07 04:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0005_alter_bulletin_options_alter_rubric_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletin',
            name='create_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 6, 7, 4, 26, 58, 891509), verbose_name='Метка даты/времени создания записи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bulletin',
            name='update_timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='Метка даты/времени изменения записи'),
        ),
    ]
