# Generated by Django 4.2.11 on 2024-06-14 05:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0007_bulletin_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='description',
            field=models.TextField(help_text='Текст неограниченной длинны', validators=[django.core.validators.MinLengthValidator(10, message='Значение не может быть меньше 10 символов')], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(10, message='Значение не может быть меньше 10 символов')], verbose_name='Название'),
        ),
    ]
