# Generated by Django 4.2.11 on 2024-06-26 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0008_alter_bulletin_description_alter_bulletin_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_query_name='bbs', to='bb.rubric', verbose_name='Рубрика'),
        ),
    ]
