# Generated by Django 4.2.14 on 2024-09-16 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0010_alter_bulletin_rubric'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletin',
            name='active_flag',
            field=models.BooleanField(default=True, verbose_name='Флаг активности объявления'),
        ),
    ]
