# Generated by Django 4.2.14 on 2024-11-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0012_alter_bulletin_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='img', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.RemoveField(
            model_name='bulletin',
            name='picture',
        ),
        migrations.AddField(
            model_name='bulletin',
            name='pictures',
            field=models.ManyToManyField(to='bb.picture', verbose_name='Изображения'),
        ),
    ]
