# Generated by Django 4.2.14 on 2024-11-13 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bb', '0013_picture_remove_bulletin_picture_bulletin_pictures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulletin',
            name='pictures',
        ),
        migrations.AddField(
            model_name='picture',
            name='bb',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bb.bulletin'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='picture',
            name='picture',
            field=models.ImageField(upload_to='img', verbose_name='Изображение'),
        ),
    ]
